# Exported from Render on 2024-06-01T07:27:50Z
services:
- type: web
  name: fpaccess
  runtime: ruby
  repo: https://github.com/crlxltbr/fp_access
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"